version: "3.7"
   
services:

  scraper:
    build: scraper
    restart: always
    volumes:
      - ./scraper/src:/code
    command: python prova.py
    env_file:
      - scraper/.env
    links:
      - chrome

  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=