version: "3.7"
   
services:

  scraper:
    build: scraper
    restart: always
    volumes:
      - ./scraper/src:/code
    command: python sysbo_scraper.py
    depends_on:
      - hub
    env_file:
      - scraper/.env
